language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake

script:
  - cmake -S linux -B build
  - cmake --build build -j
  - ctest --output-on-failure --test-dir build
